// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohouzhofisecbygwjwlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ob3V6aG9maXNlY2J5Z3dqd2xxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3NTY3MDYsImV4cCI6MjA4NzMzMjcwNn0.9QzKZwxFCNsrYi7fESkWFh1ZCNM6b8xyFD0WLHLmgG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});